config/routes.rb
Rails.application.routes.draw do
  resources :tweeets
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "tweeets#index"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweeet.rb
class Tweeet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweeets_controller.rb
class TweeetsController < ApplicationController
  before_action :set_tweeet, only: %i[ show edit update destroy ]

  # GET /tweeets or /tweeets.json
  def index
    @tweeets = Tweeet.all
  end

  # GET /tweeets/1 or /tweeets/1.json
  def show
  end

  # GET /tweeets/new
  def new
    @tweeet = Tweeet.new
  end

  # GET /tweeets/1/edit
  def edit
  end

  # POST /tweeets or /tweeets.json
  def create
    @tweeet = Tweeet.new(tweeet_params)

    respond_to do |format|
      if @tweeet.save
        format.html { redirect_to tweeet_url(@tweeet), notice: "Tweeet was successfully created." }
        format.json { render :show, status: :created, location: @tweeet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweeets/1 or /tweeets/1.json
  def update
    respond_to do |format|
      if @tweeet.update(tweeet_params)
        format.html { redirect_to tweeet_url(@tweeet), notice: "Tweeet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweeet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweeet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweeets/1 or /tweeets/1.json
  def destroy
    @tweeet.destroy

    respond_to do |format|
      format.html { redirect_to tweeets_url, notice: "Tweeet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweeet
      @tweeet = Tweeet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweeet_params
      params.require(:tweeet).permit(:tweeet)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweeets_helper.rb
module TweeetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <% if flash[:notice] %>
        <div class="notification is-primary global-notification">
          <p class="notice"><% notice %></p>
        </div>
      <% end %>
      <% if flash[:alert] %>
        <div class="notification is-danger global-notification">
          <p class="alert"><% alert %>
        </div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/tweeets/_form.html.erb
<%= form_with(model: tweeet) do |form| %>
  <% if tweeet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweeet.errors.count, "error") %> prohibited this tweeet from being saved:</h2>

      <ul>
        <% tweeet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tweeet, style: "display: block" %>
    <%= form.text_area :tweeet %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweeets/_tweeet.html.erb
<div id="<%= dom_id tweeet %>">
  <p>
    <strong>Tweeet:</strong>
    <%= tweeet.tweeet %>
  </p>

</div>

app/views/tweeets/edit.html.erb
<h1>Editing tweeet</h1>

<%= render "form", tweeet: @tweeet %>

<br>

<div>
  <%= link_to "Show this tweeet", @tweeet %> |
  <%= link_to "Back to tweeets", tweeets_path %>
</div>

app/views/tweeets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tweeets</h1>

<div id="tweeets">
  <% @tweeets.each do |tweeet| %>
    <%= render tweeet %>
    <p>
      <%= link_to "Show this tweeet", tweeet %>
    </p>
  <% end %>
</div>

<%= link_to "New tweeet", new_tweeet_path %>

app/views/tweeets/new.html.erb
<h1>New tweeet</h1>

<%= render "form", tweeet: @tweeet %>

<br>

<div>
  <%= link_to "Back to tweeets", tweeets_path %>
</div>

app/views/tweeets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweeet %>

<div>
  <%= link_to "Edit this tweeet", edit_tweeet_path(@tweeet) %> |
  <%= link_to "Back to tweeets", tweeets_path %>

  <%= button_to "Destroy this tweeet", @tweeet, method: :delete %>
</div>